# AiDemy Configuration
# This is an enhanced version of the original Google Codelab project configuration

# Application Settings
app:
  name: "AiDemy"
  version: "1.0.0"
  debug: false
  host: "0.0.0.0"
  port: 8080

# Google Cloud Settings
gcp:
  project_id: "${GOOGLE_CLOUD_PROJECT}"
  region: "us-central1"
  storage:
    course_bucket: "${COURSE_BUCKET_NAME}"
    assignment_bucket: "${ASSIGNMENT_BUCKET_NAME}"
  vertex_ai:
    model: "gemini-1.0-pro"
    max_tokens: 1024
    temperature: 0.7

# Database Settings
database:
  host: "${DB_HOST}"
  port: 5432
  name: "${DB_NAME}"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"

# Security Settings
security:
  rate_limit:
    requests_per_minute: 100
    requests_per_hour: 1000
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE"]
    allowed_headers: ["Content-Type", "Authorization"]

# Logging Settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/aidemy.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# Cache Settings
cache:
  enabled: true
  type: "redis"
  host: "localhost"
  port: 6379
  ttl: 3600  # 1 hour

# API Settings
api:
  version: "v1"
  prefix: "/api/v1"
  timeout: 30
  retry_attempts: 3

# Feature Flags
features:
  enable_audio_generation: true
  enable_quiz_generation: true
  enable_assignment_grading: true
  enable_book_recommendations: true
  enable_teaching_plan_generation: true

# Monitoring Settings
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_path: "/health"
  prometheus:
    enabled: true
    path: "/metrics"

# Development Settings
development:
  mock_ai_responses: false
  mock_database: false
  enable_debug_endpoints: false
  log_sql_queries: false

# Testing Settings
testing:
  mock_external_services: true
  use_test_database: true
  clear_data_on_startup: true 